# Generated by Django 5.0.6 on 2024-09-26 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'amount'], name='transaction_date_1eedda_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['description'], name='transaction_descrip_ea58c0_idx'),
        ),
    ]
